### ISSUE TITLE
Please release 0.1.1 to pypi

### ISSUE THREAD

**Issue by waynr** [mosquito/carbon-client#2]
Since https://github.com/mosquito/carbon-client/pull/1 was a bug fix, bumping the patch-level should be sufficient.

**Comment by mosquito** [comment]
Thank you. I already published current version as a 0.1.2.

**Comment by waynr** [comment]
@mosquito do you mean `0.2.0`? I see it now, was just confused I guess because I didn't see a new release listed here on github. I'm also curious where the old `0.1.0` went since it doesn't appear to be on pypi any longer. Not that it bothers me much but I suspect it might annoy existing users who are hard-pinned to `0.1.0`.

**Comment by mosquito** [comment]
Excuse me. I uploaded the broken version today. I will refactor it. 0.2.0 removed from pypi.
